"""
GitHub API client for automated PR creation.

Flow per incident:
  1. Resolve owner/repo from the repo URL
  2. Get the default branch SHA
  3. Create branch  healer/incident-{trace_id}
  4. Commit a file  healer-incidents/{trace_id}.md  with RCA + fix details
  5. Open a PR targeting the default branch
"""
import base64
import logging
import re
from datetime import datetime, timezone
from typing import Optional, Dict, Any

import httpx

logger = logging.getLogger("healer.github")

GH_API = "https://api.github.com"


def _owner_repo(repo_url: str):
    """Extract (owner, repo) from a GitHub URL."""
    m = re.search(r"github\.com[/:]([^/]+)/([^/\s]+?)(?:\.git)?$", repo_url)
    if not m:
        raise ValueError(f"Cannot parse GitHub repo URL: {repo_url}")
    return m.group(1), m.group(2).rstrip("/")


def _headers(token: str) -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _incident_md(incident: Dict[str, Any]) -> str:
    ts = incident.get("detected_at", "")[:19].replace("T", " ")
    error_types = ", ".join(incident.get("error_types") or [])
    return f"""# Healer Incident Report

| Field | Value |
|-------|-------|
| **Service** | {incident.get("service_name", "")} |
| **Detected** | {ts} UTC |
| **Blast Radius** | {incident.get("blast_radius", "")} |
| **Error Types** | `{error_types}` |
| **Trace ID** | `{incident.get("trace_id", "")}` |

## Root Cause

{incident.get("root_cause", "")}

## Fix Suggestion

{incident.get("fix_suggestion", "")}

## PR Description

{incident.get("pr_description", "")}

---
*Auto-generated by [Healer](https://github.com) — AI Self-Healing Incident Assistant*
"""


async def create_pr(
    token: str,
    repo_url: str,
    incident: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Create a GitHub PR for the given incident.
    Returns dict with keys: pr_url, pr_number, pr_status, branch.
    """
    if not token:
        return {"pr_status": "skipped", "pr_url": None, "pr_number": None, "branch": None, "error": "No GITHUB_TOKEN"}

    try:
        owner, repo = _owner_repo(repo_url)
    except ValueError as e:
        return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None, "error": str(e)}

    trace_short = (incident.get("trace_id") or "unknown")[:12]
    branch_name = f"healer/incident-{trace_short}"
    file_path = f"healer-incidents/{trace_short}.md"
    error_types = incident.get("error_types") or []
    pr_title = f"[Healer] {incident.get('blast_radius','')} — {', '.join(error_types[:2])}"

    headers = _headers(token)

    async with httpx.AsyncClient(timeout=15.0) as client:
        # 1. Get default branch
        r = await client.get(f"{GH_API}/repos/{owner}/{repo}", headers=headers)
        if r.status_code != 200:
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None,
                    "error": f"Repo not found: {r.status_code}"}
        default_branch = r.json()["default_branch"]

        # 2. Get tip SHA of default branch
        r = await client.get(f"{GH_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}", headers=headers)
        if r.status_code != 200:
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None,
                    "error": f"Cannot get branch ref: {r.status_code}"}
        base_sha = r.json()["object"]["sha"]

        # 3. Create branch (ignore 422 = already exists)
        r = await client.post(
            f"{GH_API}/repos/{owner}/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )
        if r.status_code not in (201, 422):
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None,
                    "error": f"Cannot create branch: {r.status_code}"}

        # 4. Commit incident markdown file
        content_b64 = base64.b64encode(_incident_md(incident).encode()).decode()
        # Check if file exists (for update SHA)
        existing = await client.get(
            f"{GH_API}/repos/{owner}/{repo}/contents/{file_path}",
            headers=headers,
            params={"ref": branch_name},
        )
        payload: Dict[str, Any] = {
            "message": f"healer: incident report {trace_short}",
            "content": content_b64,
            "branch": branch_name,
        }
        if existing.status_code == 200:
            payload["sha"] = existing.json()["sha"]

        r = await client.put(
            f"{GH_API}/repos/{owner}/{repo}/contents/{file_path}",
            headers=headers,
            json=payload,
        )
        if r.status_code not in (200, 201):
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None,
                    "error": f"Cannot commit file: {r.status_code} {r.text[:200]}"}

        # 5. Create PR
        pr_body = (
            f"**Blast Radius:** `{incident.get('blast_radius','')}`\n\n"
            f"**Root Cause:** {incident.get('root_cause','')}\n\n"
            f"**Fix:** {incident.get('fix_suggestion','')}\n\n"
            f"---\n"
            f"Auto-generated by Healer for trace `{incident.get('trace_id','')}`"
        )
        r = await client.post(
            f"{GH_API}/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": pr_title,
                "body": pr_body,
                "head": branch_name,
                "base": default_branch,
                "draft": False,
            },
        )
        # 422 can mean PR already exists for this branch
        if r.status_code == 422:
            # Try to find the existing PR
            search = await client.get(
                f"{GH_API}/repos/{owner}/{repo}/pulls",
                headers=headers,
                params={"head": f"{owner}:{branch_name}", "state": "open"},
            )
            if search.status_code == 200 and search.json():
                pr = search.json()[0]
                return {"pr_status": "created", "pr_url": pr["html_url"],
                        "pr_number": pr["number"], "branch": branch_name, "error": None}
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": branch_name,
                    "error": f"PR creation failed: {r.text[:200]}"}

        if r.status_code != 201:
            return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": branch_name,
                    "error": f"PR creation failed: {r.status_code} {r.text[:200]}"}

        pr = r.json()
        logger.info(f"PR created: {pr['html_url']}")
        return {
            "pr_status": "created",
            "pr_url": pr["html_url"],
            "pr_number": pr["number"],
            "branch": branch_name,
            "error": None,
        }

    # unreachable but satisfies return type
    return {"pr_status": "failed", "pr_url": None, "pr_number": None, "branch": None, "error": "Unknown"}
